[package]
name = "bevy_2d_inverse_kinematics"
version = "0.5.0"
edition = "2021"
description = "A 2D inverse kinematics plugin for Bevy"
repository = "https://github.com/ntibi/bevy_2d_inverse_kinematics"
readme = "README.md"
license-file = "LICENSE"
keywords = ["bevy", "fabrik", "2d", "inverse-kinematics", "animation"]
categories = ["game-development", "simulation", "games"]
exclude = ["assets/", "misc/", ".github/"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.17.2" }

[dev-dependencies]
bevy_egui = "0.38.0"
bevy-inspector-egui = { version = "0.34.0", default-features = true }
